# Generated by Django 5.0.7 on 2024-08-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogAndReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog_and_review_images')),
                ('title', models.CharField(max_length=255)),
                ('excerpt', models.TextField()),
                ('affiliate_link', models.CharField(blank=True, max_length=2083)),
                ('date_and_time_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Blogs & Reviews',
                'ordering': ('-date_and_time_created',),
            },
        ),
        migrations.CreateModel(
            name='HomepageSoftware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='homepage_software_images')),
                ('title', models.CharField(max_length=255)),
                ('price', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('affiliate_link', models.CharField(max_length=2083)),
                ('date_and_time_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Homepage Software Only',
                'ordering': ('-date_and_time_created',),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('date_and_time_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-date_and_time_created',),
            },
        ),
    ]
