# Generated by Django 5.0.7 on 2024-08-07 12:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-date_created',)},
        ),
        migrations.RemoveField(
            model_name='message',
            name='date_and_time_created',
        ),
        migrations.AddField(
            model_name='message',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
